poll_interval: 60s
sample_age_enabled: true

devices:
  - name: "ion_7400"
    protocol: "modbus-tcp"
    address: "192.168.1.65"
    port: 502
    timeout: 1s
    labels:
      site: "building_A"
      role: "main_meter"

    slaves:
      - name: "ion_7400"
        slave_id: 1
        offset: 1
        labels:
          location: "floor_1"
          unit: "energetics"
        modbus_registers:
          - register: 3110
            function_code: 3
            name: "freq_mean"
            description: "Mean frequency"
            words: 2
            datatype: "F32BE"
            unit: "Hz"
            gain: 1
            ignore_negative: true
            flags:

  - name: "logger_3000"
    protocol: "modbus-tcp"
    address: "192.168.1.90"
    port: 502
    timeout: 1s

    slaves:
      - name: "SG250HX_COM2_1"
        slave_id: 1
        offset: 1
        modbus_registers: &logger_regs
          - register: 5031
            function_code: 4
            name: "total_active_power"
            description: "Total active power"
            words: 2
            datatype: "U32LE"
            unit: "W"
            gain: 1
            flags:
          - register: 5008
            function_code: 4
            name: "internal_temperature"
            description: "Internal temperature"
            words: 1
            datatype: "S16"
            unit: "°C"
            gain: 0.1
            flags:
          - register: 4990
            function_code: 4
            name: "serial_id"
            description: "Serial number"
            words: 10
            datatype: "UTF-8"
            unit: ""
            gain: 1
            flags:

      - name: "SG250HX_COM2_2"
        slave_id: 2
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM2_4"
        slave_id: 3
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM2_6"
        slave_id: 5
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM2_7"
        slave_id: 6
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM3_8"
        slave_id: 7
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM2_8"
        slave_id: 8
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM3_9"
        slave_id: 9
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM3_10"
        slave_id: 10
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM3_11"
        slave_id: 11
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM3_12"
        slave_id: 12
        offset: 1
        modbus_registers: *logger_regs

      - name: "SG250HX_COM2_5"
        slave_id: 13
        offset: 1
        modbus_registers: *logger_regs